### PR TITLE
com.openai.unity 4.8.7

### PR DESCRIPTION
**Pull request by damiant3**
- Add ToString and string operator to Moderation.Scores

### CODE REVIEW

**Review by StephenHodgson — CHANGES_REQUESTED** [review]
I don't think a string builder is really necessary here. Just as fast to string concat.

Also let's be sure to version and add release notes

**Comment by damiant3** [comment]
Surely!  Do you think it's worth a release for this one little thing?

**Comment by StephenHodgson** [comment]
Every commit to main bumps the version.

**Comment by damiant3** [comment]
Hope I did it right!

**Review by StephenHodgson — APPROVED** [review]

**Pull request merged**
