### PR TITLE
com.openai.unity 8.4.0

### PR DESCRIPTION
**Pull request by StephenHodgson**
- Add realtime support
- Added `o1`, `o1-mini`, `gpt-4o-mini`, and `gpt-4o-realtime`, `gpt-4o-audio` model convenience properties
- Added Assistant and Realtime sample scenes
- Added FileEndpoint.DownloadFileBytesAsync for WebGL platform apps
- Fixed some bugs with function invocations
- Fixed `strict` for built in `FunctionAttribute` defined tools
- Fixed `FunctionAttribute` tool generated names so they aren't too long
- Refactored `Tools` and `ToolCalls`. There is more of a distinction now in `ChatResponses`
- Refactored `SpeechRequest`, and deprecated `SpeechVoice` enum in favor of new `Voice` class
- Refactored `OpenAI.Chat` to support new audio modalities and output audio

### CODE REVIEW

**Comment by Bodekaer** [comment]
Amazing! Testing out now.

**Comment by StephenHodgson** [comment]
> Amazing! Testing out now.

Still a WIP! nothing really hooked up just yet

**Comment by Bodekaer** [comment]
Ahh, no worries. Thanks of the heads up :) Just ping me when alpha testing opens up :)

**Comment by yosun** [comment]
hmm tried realtime sample

```
Utilities.WebRequestRest.RestException: [POST:400] https://api.openai.com/v1/chat/completions Failed!
{
  "request": {
    "url": "https://api.openai.com/v1/chat/completions",
    "body": {
      "messages": [
        {
          "role": "system",
          "content": "You are a helpful assistant.\n- If an image is requested then use \"![Image](output.jpg)\" to display it.\n- When performing function calls, use the defaults unless explicitly told to use a specific value.\n- Images should always be generated in base64."
        },
        {
          "role": "user",
          "content": "Hey, so tell me about yourself."
        }
      ],
      "model": "gpt-4o",
      "response_format": {
        "type": "text"
      },
      "stream": true,
      "tools": [
        {
          "type": "function",
          "function": {
            "name": "OpenAI_Images_ImagesEndpoint_GenerateImageAsync",
            "parameters": {
              "type": "object",
              "properties": {
                "request": {
                  "$ref": "#/definitions/OpenAI.Images.ImageGenerationRequest"
                }
              },
              "definitions": {
                "OpenAI.Images.ImageGenerationRequest": {
                  "type": "object",
                  "properties": {
                    "model": {
                      "type": "string",
                      "description": "The model to use for image generation.",
                      "default": "dall-e-2",
                      "enum": [
                        "dall-e-3",
                        "dall-e-2"
                      ]
                    },
                    "prompt": {
                      "type": "string",
                      "description": "A text description of the desired image(s). The maximum length is 1000 characters for dall-e-2 and 4000 characters for dall-e-3."
                    },
                    "n": {
                      "type": "integer",
                      "description": "The number of images to generate. Must be between 1 and 10. For dall-e-3, only n=1 is supported.",
                      "default": 1
                    },
                    "quality": {
                      "type": "string",
                      "description": "The quality of the image that will be generated. hd creates images with finer details and greater consistency across the image. This param is only supported for dall-e-3.",
                      "enum": [
                        "standard",
                        "hd"
                      ]
                    },
                    "response_format": {
                      "type": "string",
                      "enum": [
                        "Url",
                        "B64_Json"
                      ],
                      "description": "The format in which the generated images are returned. Must be one of url or b64_json."
                    },
                    "size": {
                      "type": "string",
                      "description": "The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024 for dall-e-2. Must be one of 1024x1024, 1792x1024, or 1024x1792 for dall-e-3 models.",
                      "default": "1024x1024",
                      "enum": [
                        "256x256",
                        "512x512",
                        "1024x1024",
                        "1792x1024",
                        "1024x1792",
                        "1024x1024"
                      ]
                    },
                    "style": {
                      "type": "string",
                      "description": "The style of the generated images. Must be one of vivid or natural. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images. This param is only supported for dall-e-3.",
                      "enum": [
                        "vivid",
                        "natural"
                      ]
                    },
                    "user": {
                      "type": "string",
                      "description": "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse."
                    }
                  },
                  "required": [
                    "model",
                    "prompt",
                    "n",
                    "response_format",
                    "size"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "request"
              ],
              "additionalProperties": false
            },
            "strict": true
          }
        }
      ],
      "tool_choice": "auto"
    }
  },
  "response": {
    "code": 400,
    "headers": {
      "Date": "Tue, 15 Oct 2024 01:42:42 GMT",
      "Content-Type": "application/json",
      "Content-Length": "301",
      "Connection": "keep-alive",
      "access-control-expose-headers": "X-Request-ID",
      "openai-organization": "areality3d-permute",
      "openai-processing-ms": "25",
      "openai-version": "2020-10-01",
      "x-ratelimit-limit-requests": "500",
      "x-ratelimit-limit-tokens": "30000",
      "x-ratelimit-remaining-requests": "499",
      "x-ratelimit-remaining-tokens": "29912",
      "x-ratelimit-reset-requests": "120ms",
      "x-ratelimit-reset-tokens": "176ms",
      "x-request-id": "req_7dcc73c66624c05eef8d66c1552fd689",
      "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
      "CF-Cache-Status": "DYNAMIC",
      "X-Content-Type-Options": "nosniff",
      "Server": "cloudflare",
      "CF-RAY": "8d2c1d3468a215e7-SJC",
      "alt-svc": "h3=\":443\"; ma=86400"
    },
    "data": 301,
    "body": {
      "error": {
        "message": "Invalid schema for function 'OpenAI_Images_ImagesEndpoint_GenerateImageAsync': In context=('properties', 'n'), 'default' is not permitted.",
        "type": "invalid_request_error",
        "param": "tools[0].function.parameters",
        "code": "invalid_function_parameters"
      }
    },
    "error": "HTTP/1.1 400 Bad Request\n"
  }
}
  at Utilities.WebRequestRest.Rest.Validate (Utilities.WebRequestRest.Response response, System.Boolean debug, System.String methodName) [0x00020] in /Users/mbp16_2022_m1max/Downloads/com.openai.unity-a144a58e662cba09509c341fa2f4425460cad2d9/OpenAI/Library/PackageCache/com.utilities.rest@3.2.3/Runtime/Rest.cs:1442 
  at OpenAI.Chat.ChatEndpoint.StreamCompletionAsync (OpenAI.Chat.ChatRequest chatRequest, System.Func`2[T,TResult] resultHandler, System.Boolean streamUsage, System.Threading.CancellationToken cancellationToken) [0x00152] in /Users/mbp16_2022_m1max/Downloads/com.openai.unity-a144a58e662cba09509c341fa2f4425460cad2d9/OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs:163 
  at OpenAI.Chat.ChatEndpoint.StreamCompletionAsync (OpenAI.Chat.ChatRequest chatRequest, System.Action`1[T] resultHandler, System.Boolean streamUsage, System.Threading.CancellationToken cancellationToken) [0x0004e] in /Users/mbp16_2022_m1max/Downloads/com.openai.unity-a144a58e662cba09509c341fa2f4425460cad2d9/OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs:69 
  at OpenAI.Samples.Chat.ChatBehaviour.SubmitChat () [0x001a8] in /Users/mbp16_2022_m1max/Downloads/com.openai.unity-a144a58e662cba09509c341fa2f4425460cad2d9/OpenAI/Assets/Samples/Chat/ChatBehaviour.cs:121 
UnityEngine.Debug:LogError (object)
OpenAI.Samples.Chat.ChatBehaviour/<SubmitChat>d__21:MoveNext () (at Assets/Samples/Chat/ChatBehaviour.cs:146)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<OpenAI.Chat.ChatResponse>:SetException (System.Exception)
OpenAI.Chat.ChatEndpoint/<StreamCompletionAsync>d__7:MoveNext () (at Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs:69)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<OpenAI.Chat.ChatResponse>:SetException (System.Exception)
OpenAI.Chat.ChatEndpoint/<StreamCompletionAsync>d__10:MoveNext () (at Packages/com.openai.unity/Runtime/Chat/ChatEndpoint.cs:167)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Utilities.WebRequestRest.Response>:SetResult (Utilities.WebRequestRest.Response)
Utilities.WebRequestRest.Rest/<PostAsync>d__20:MoveNext () (at Library/PackageCache/com.utilities.rest@3.2.3/Runtime/Rest.cs:263)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Utilities.WebRequestRest.Response>:SetResult (Utilities.WebRequestRest.Response)
Utilities.WebRequestRest.Rest/<SendAsync>d__56:MoveNext () (at Library/PackageCache/com.utilities.rest@3.2.3/Runtime/Rest.cs:1422)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
Utilities.Async.AwaiterExtensions:RunOnUnityScheduler (System.Action) (at Library/PackageCache/com.utilities.async@2.1.7/Runtime/Async/AwaiterExtensions.cs:297)
Utilities.Async.SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception) (at Library/PackageCache/com.utilities.async@2.1.7/Runtime/Async/SimpleCoroutineAwaiter.cs:115)
Utilities.Async.AwaiterExtensions/<ReturnAsyncOperation>d__31:MoveNext () (at Library/PackageCache/com.utilities.async@2.1.7/Runtime/Async/AwaiterExtensions.cs:397)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

```

**Comment by yosun** [comment]
should websockets be used instead of rest?

**Comment by StephenHodgson** [comment]
> hmm tried realtime sample
> should websockets be used instead of rest?

Sample scenes have not been updated yet.

**Comment by Bodekaer** [comment]
Hey @StephenHodgson, do you have an ETA for a first alpha/beta of this API?
I imagine the implementation is far more complicated than earlier API additions. Let me know if we can support in any way.

**Comment by StephenHodgson** [comment]
@Bodekaer been a little backed up with client work. Not really sure I have ETA right now.

**Comment by StephenHodgson** [comment]
@Bodekaer I think we're about ready to start testing this out. I got everything working except for microphone input.

Checkout the new realtime sample scene.

**Pull request merged**
