### PR TITLE
Update Message.cs serialization for better in editor list layout

### PR DESCRIPTION
**Pull request by imineti**
What I changed:
Updated Message.cs so that the first parameter is the name variable.

Reason:
When creating a list of messages using "List<Message>() messages = new List<Message>();" it creates a list of message objects in the inspector but each message on the list shows as 'element 0', 'element 1', 'element 2' etc., but if the first parameter is a string called 'name' the messages on the list will be named after the parameter name.

This is useful because now we can have all the messages on our list of messages in the inspector collapsed and still see what they are called which means we don't need to have every item on the list expanded to see what is what.

It looks nicer, it's more convenient and will allow for a slightly faster workflow when using lists of messages in the inspector. Also, just why not? The variable was already there and so it only makes sense.

(PS I am using the OpenUPM version so I can't change the script myself even in my own project so you will need to test this first just in case of human error)

### CODE REVIEW

**Comment by StephenHodgson** [comment]
This is a great change but I'm afraid it's also a breaking change.

**Comment by imineti** [comment]
I see my error I didn't consider that you would have to alter all the instances where Message is called and put the name parameter first and also then the name parameter would no longer be optional. 

I need to go to sleep but I will make an Attribute tomorrow that will change the element names based on the name variable even though it is not the first parameter.

**Comment by StephenHodgson** [comment]
I think what I can do in the meantime is write a custom property drawer for the messages.

**Comment by StephenHodgson** [comment]
I think that it's fun to move the position of the field, but we want to revert the constructor changes.

And I'll be fine with this.

**Comment by imineti** [comment]
I've made the changes you suggested, I put everything back how it was and only moved the field. I was able to test this time and seems to be working. Thank you.

**Comment by StephenHodgson** [comment]
One last suggested changes to bump the version number in the package.json file

**Comment by imineti** [comment]
Thank you, I'm still learning. I'll remember to bump the version number next time.

**Review by StephenHodgson — APPROVED** [review]

**Pull request merged**
